In [9]:
from Libraries_vancouver_weather import v2013_df1
from Libraries_vancouver_weather import v2014_df1
from Libraries_vancouver_weather import v2015_df1
from Libraries_vancouver_weather import v2016_df1
from Libraries_vancouver_weather import v2017_df1
from Libraries_vancouver_weather import v2018_df1
from Libraries_vancouver_weather import v2019_df1
from Libraries_vancouver_weather import v2020_df1
from Libraries_vancouver_weather import v2021_df1
from Libraries_vancouver_weather import v2022_df1

In [10]:
v2013_df1

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (Â°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-123.18,49.19,VANCOUVER INTL A,1108395,2013-01-01,2013,1,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-123.18,49.19,VANCOUVER INTL A,1108395,2013-01-02,2013,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-123.18,49.19,VANCOUVER INTL A,1108395,2013-01-03,2013,1,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-123.18,49.19,VANCOUVER INTL A,1108395,2013-01-04,2013,1,4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-123.18,49.19,VANCOUVER INTL A,1108395,2013-01-05,2013,1,5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,-123.18,49.19,VANCOUVER INTL A,1108395,2013-12-27,2013,12,27,NaN,NaN,...,NaN,NaN,NaN,M,0.0,NaN,NaN,M,NaN,M
361,-123.18,49.19,VANCOUVER INTL A,1108395,2013-12-28,2013,12,28,NaN,6.8,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,<31,NaN
362,-123.18,49.19,VANCOUVER INTL A,1108395,2013-12-29,2013,12,29,NaN,5.8,...,0.0,NaN,1.2,NaN,NaN,NaN,NaN,NaN,<31,NaN
363,-123.18,49.19,VANCOUVER INTL A,1108395,2013-12-30,2013,12,30,NaN,7.0,...,0.0,NaN,0.0,T,NaN,NaN,NaN,NaN,<31,NaN
364,-123.18,49.19,VANCOUVER INTL A,1108395,2013-12-31,2013,12,31,NaN,7.4,...,0.0,NaN,2.2,NaN,NaN,NaN,NaN,NaN,<31,NaN

In [11]:
column_headers = v2014_df1.columns.tolist()
column_headers

['Longitude (x)',
 'Latitude (y)',
 'Station Name',
 'Climate ID',
 'Date/Time',
 'Year',
 'Month',
 'Day',
 'Data Quality',
 'Max Temp (Â°C)',
 'Max Temp Flag',
 'Min Temp (Â°C)',
 'Min Temp Flag',
 'Mean Temp (Â°C)',
 'Mean Temp Flag',
 'Heat Deg Days (Â°C)',
 'Heat Deg Days Flag',
 'Cool Deg Days (Â°C)',
 'Cool Deg Days Flag',
 'Total Rain (mm)',
 'Total Rain Flag',
 'Total Snow (cm)',
 'Total Snow Flag',
 'Total Precip (mm)',
 'Total Precip Flag',
 'Snow on Grnd (cm)',
 'Snow on Grnd Flag',
 'Dir of Max Gust (10s deg)',
 'Dir of Max Gust Flag',
 'Spd of Max Gust (km/h)',
 'Spd of Max Gust Flag']

In [12]:
v2015_df1.isna().sum()

Longitude (x)                  0
Latitude (y)                   0
Station Name                   0
Climate ID                     0
Date/Time                      0
Year                           0
Month                          0
Day                            0
Data Quality                 365
Max Temp (Â°C)                  1
Max Temp Flag                363
Min Temp (Â°C)                  0
Min Temp Flag                363
Mean Temp (Â°C)                 1
Mean Temp Flag               363
Heat Deg Days (Â°C)             1
Heat Deg Days Flag           363
Cool Deg Days (Â°C)             1
Cool Deg Days Flag           363
Total Rain (mm)                5
Total Rain Flag              335
Total Snow (cm)                2
Total Snow Flag              362
Total Precip (mm)              4
Total Precip Flag            335
Snow on Grnd (cm)              1
Snow on Grnd Flag            365
Dir of Max Gust (10s deg)    156
Dir of Max Gust Flag         363
Spd of Max Gust (km/h)         2
Spd of Max Gust Flag         363
dtype: int64

In [13]:
v2013_df1.dtypes

Longitude (x)                float64
Latitude (y)                 float64
Station Name                  object
Climate ID                     int64
Date/Time                     object
Year                           int64
Month                          int64
Day                            int64
Data Quality                 float64
Max Temp (Â°C)                float64
Max Temp Flag                 object
Min Temp (Â°C)                float64
Min Temp Flag                 object
Mean Temp (Â°C)               float64
Mean Temp Flag                object
Heat Deg Days (Â°C)           float64
Heat Deg Days Flag            object
Cool Deg Days (Â°C)           float64
Cool Deg Days Flag            object
Total Rain (mm)              float64
Total Rain Flag               object
Total Snow (cm)              float64
Total Snow Flag               object
Total Precip (mm)            float64
Total Precip Flag             object
Snow on Grnd (cm)            float64
Snow on Grnd Flag             object
Dir of Max Gust (10s deg)    float64
Dir of Max Gust Flag          object
Spd of Max Gust (km/h)        object
Spd of Max Gust Flag          object
dtype: object

In [20]:
v2014_df1

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (Â°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-123.18,49.19,VANCOUVER INTL A,1108395,2014-01-01,2014,1,1,NaN,6.5,...,0.0,NaN,0.8,NaN,NaN,NaN,NaN,NaN,<31,NaN
1,-123.18,49.19,VANCOUVER INTL A,1108395,2014-01-02,2014,1,2,NaN,7.5,...,0.0,NaN,13.8,NaN,NaN,NaN,28.0,NaN,80,NaN
2,-123.18,49.19,VANCOUVER INTL A,1108395,2014-01-03,2014,1,3,NaN,6.8,...,0.0,NaN,0.0,NaN,NaN,NaN,28.0,NaN,76,NaN
3,-123.18,49.19,VANCOUVER INTL A,1108395,2014-01-04,2014,1,4,NaN,4.9,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,<31,NaN
4,-123.18,49.19,VANCOUVER INTL A,1108395,2014-01-05,2014,1,5,NaN,4.7,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,<31,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,-123.18,49.19,VANCOUVER INTL A,1108395,2014-12-27,2014,12,27,NaN,6.5,...,0.0,NaN,11.0,NaN,0.0,NaN,28.0,NaN,54,NaN
361,-123.18,49.19,VANCOUVER INTL A,1108395,2014-12-28,2014,12,28,NaN,4.8,...,0.0,NaN,0.0,T,0.0,NaN,30.0,NaN,33,NaN
362,-123.18,49.19,VANCOUVER INTL A,1108395,2014-12-29,2014,12,29,NaN,5.7,...,0.0,NaN,0.0,NaN,0.0,NaN,7.0,NaN,33,NaN
363,-123.18,49.19,VANCOUVER INTL A,1108395,2014-12-30,2014,12,30,NaN,1.6,...,0.0,NaN,0.0,NaN,0.0,NaN,8.0,NaN,37,NaN
364,-123.18,49.19,VANCOUVER INTL A,1108395,2014-12-31,2014,12,31,NaN,2.1,...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,<31,NaN

In [19]:
v2014_df1.isna().sum()

Longitude (x)                  0
Latitude (y)                   0
Station Name                   0
Climate ID                     0
Date/Time                      0
Year                           0
Month                          0
Day                            0
Data Quality                 365
Max Temp (Â°C)                  1
Max Temp Flag                364
Min Temp (Â°C)                  0
Min Temp Flag                364
Mean Temp (Â°C)                 1
Mean Temp Flag               364
Heat Deg Days (Â°C)             1
Heat Deg Days Flag           364
Cool Deg Days (Â°C)             1
Cool Deg Days Flag           364
Total Rain (mm)                6
Total Rain Flag              338
Total Snow (cm)                1
Total Snow Flag              360
Total Precip (mm)              6
Total Precip Flag            336
Snow on Grnd (cm)             58
Snow on Grnd Flag            364
Dir of Max Gust (10s deg)    151
Dir of Max Gust Flag         364
Spd of Max Gust (km/h)         1
Spd of Max Gust Flag         364
dtype: int64

In [24]:
selected_columns= [
 'Year',
 'Month',
 'Day','Max Temp (Â°C)',
 'Min Temp (Â°C)',
 'Mean Temp (Â°C)',
 'Heat Deg Days (Â°C)',
 'Cool Deg Days (Â°C)',
 'Total Rain (mm)',
 'Total Snow (cm)',
 'Total Precip (mm)',
 'Dir of Max Gust (10s deg)',
 'Spd of Max Gust (km/h)']

v2014_selected= v2014_df1[selected_columns].copy()

In [25]:
v2014_selected

,Year,Month,Day,Max Temp (Â°C),Min Temp (Â°C),Mean Temp (Â°C),Heat Deg Days (Â°C),Cool Deg Days (Â°C),Total Rain (mm),Total Snow (cm),Total Precip (mm),Dir of Max Gust (10s deg),Spd of Max Gust (km/h)
0,2014,1,1,6.5,3.0,4.8,13.2,0.0,0.8,0.0,0.8,NaN,<31
1,2014,1,2,7.5,5.2,6.4,11.6,0.0,13.8,0.0,13.8,28.0,80
2,2014,1,3,6.8,0.5,3.7,14.3,0.0,0.0,0.0,0.0,28.0,76
3,2014,1,4,4.9,-2.9,1.0,17.0,0.0,0.0,0.0,0.0,NaN,<31
4,2014,1,5,4.7,-3.4,0.7,17.3,0.0,0.0,0.0,0.0,NaN,<31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2014,12,27,6.5,3.5,5.0,13.0,0.0,11.0,0.0,11.0,28.0,54
361,2014,12,28,4.8,-2.3,1.3,16.7,0.0,0.0,0.0,0.0,30.0,33
362,2014,12,29,5.7,-2.4,1.7,16.3,0.0,0.0,0.0,0.0,7.0,33
363,2014,12,30,1.6,-5.2,-1.8,19.8,0.0,0.0,0.0,0.0,8.0,37
364,2014,12,31,2.1,-5.0,-1.5,19.5,0.0,0.0,0.0,0.0,NaN,<31

In [27]:
v2014_selected.isna().sum()

Year                           0
Month                          0
Day                            0
Max Temp (Â°C)                  1
Min Temp (Â°C)                  0
Mean Temp (Â°C)                 1
Heat Deg Days (Â°C)             1
Cool Deg Days (Â°C)             1
Total Rain (mm)                6
Total Snow (cm)                1
Total Precip (mm)              6
Dir of Max Gust (10s deg)    151
Spd of Max Gust (km/h)         1
dtype: int64

In [28]:
# Find the number of rows in each column that are filled with 0.0
zero_filled_rows_per_column = (v2014_selected == 0.0).sum()

zero_filled_rows_per_column

Year                           0
Month                          0
Day                            0
Max Temp (Â°C)                  0
Min Temp (Â°C)                  2
Mean Temp (Â°C)                 0
Heat Deg Days (Â°C)            51
Cool Deg Days (Â°C)           315
Total Rain (mm)              204
Total Snow (cm)              359
Total Precip (mm)            202
Dir of Max Gust (10s deg)      0
Spd of Max Gust (km/h)         0
dtype: int64